const COOKIE_MAX_AGE = 2628002880;

const TOKEN_EXPIRES_IN = 600;

const DEFAULT_PAGE = 1;

const DEFAULT_DISPLAY = 10;

module.exports = {
  COOKIE_MAX_AGE,
  TOKEN_EXPIRES_IN,
  DEFAULT_PAGE,
  DEFAULT_DISPLAY,
};
